# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='pin',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='prescription',
            name='auth',
            field=models.BooleanField(default=False),
        ),
    ]
