# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0002_auto_20160427_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='reset',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adherence',
            name='history',
            field=models.IntegerField(),
        ),
    ]
